In [11]:
import numpy as np
import pandas as pd

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태 (1, 3)


In [3]:
print(f'array1={array1.ndim}, array2={array2.ndim}, array3={array3.ndim}')

array1=1, array2=2, array3=2


In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1,2, 'array']
array2 = np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3= np.array(list3)
print(array3, array3.dtype)

['1' '2' 'array'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int = array_float.astype('int32')
print(array_int, array_int.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
# ndarray 편리하게 생성하기 -arrange,zeros,ones

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [8]:
# ndarray 차원의 크기를 변경하는 reshape()
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array2.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
# 1차원을 2차원으로 바꿀 순 없음
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [15]:
# 새로운 타입 변화 - 인자에 -1 주기
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2.shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3.shape:', array3.shape)


[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


In [16]:
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [24]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d.tolist())

#3->2
array5 =array3d.reshape(-1,1)
print(array5.tolist())
print(array5.shape)

#1->2
array6 =array1.reshape(-1,1)
print(array6.tolist())
print(array6.shape)


[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [27]:
# 단일 인덱싱

array1 = np.arange(start=1, stop=10)
print(array1)

value=array1[2]
print(value)
print(type(value))


[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int64'>


In [26]:
array1[0]=9
array1[8]=0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [30]:
array1d = np.arange(start=1, stop=10)
print(array1d.shape)
array2d = array1d.reshape(3,3)
print(array2d)

# row= , col =0
print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [35]:
#1차원 슬라이싱 row = 

array1 = np.arange(start=1,stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

# : 시작,종료 인덱스 생략 가능
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [39]:
# 2차원 슬라이싱

array1 = np.arange(start=1,stop=10)
array2d = array1.reshape(3,3)
print(array2)

print(array2d[0:2,0:2])
print(array2d[1:3,:])
print(array2d[1:3,0:3])
print(array2d[:,:])
print(array2d[:2,1:])
print(array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [40]:
print(array2d[0])
print(array2d[0].shape)

[1 2 3]
(3,)


In [42]:
# 팬시 인덱싱

array1 = np.arange(start=1,stop=10)
array2d = array1.reshape(3,3)

array3d = array2d[[0,1],2]
print(array3.tolist())

array4 = array2d[[1,2],0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[1, 2, 3]
[[4, 5], [7, 8]]
[[1, 2, 3], [4, 5, 6]]


In [44]:
# 불린 인덱싱

array1d = np.arange(start=1,stop=10)
array3 = array1d[array1d > 5]
print(array3)
print(array1d > 5)

[6 7 8 9]
[False False False False False  True  True  True  True]


In [48]:
boolean_indexes = np.array([False, False, False, False, False, True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print(array3)

indexes = np.array([5,6,7,8]) 
array4 = array1d[indexes]
print(array4)

[6 7 8 9]
[6 7 8 9]


In [53]:
# sort(), argsort()

org_array = np.array([3,1,9,5]) 
print('원본',org_array)

#np.sort
sort_array1 = np.sort(org_array)
print(sort_array1)

sort_array2 = org_array.sort()
print(sort_array2)

sort_array1_desc= np.sort(org_array)[::-1]
print('내림차순', sort_array1_desc)

원본 [3 1 9 5]
[1 3 5 9]
None
내림차순 [9 5 3 1]


In [60]:
# 정렬 - 로우 방향 axis=0, 컬럼 방향 axis=1

array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [64]:
# 정렬된 행렬 인덱스 반환 / np.argsort

org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[2 3 0 1]


In [73]:
name_array = np.array(['John', 'Mike','Salah','Szobo','Darwin'])
score_array = np.array([78, 95, 84, 98, 88])

np.argsort(score_array)

sort_indices_asc = np.argsort(score_array) # 오름차순
print(sort_indices_asc)
print(name_array)


[0 2 4 1 3]
['John' 'Mike' 'Salah' 'Szobo' 'Darwin']


In [74]:
# 선형대수 연산 -행렬 내적 전치 행렬 구하기
# 행렬 내적 - 행렬 곱, 두 행렬 A와 B의 내적 np.dot()

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])


In [75]:
dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [76]:
# 전치 행렬
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]


In [12]:
# 1차원
# 넘파이 ndarray 리스트 딕셔너리 DataFrame으로 변환

col_name1=['col1']
list1 = [1,2,3]
array1=np.array(list1)
print('array1.shape')
#리스트로 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('리스트',df_list1)

#넘파이 ndarray로 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('ndarray',df_array1)

array1.shape
리스트    col1
0     1
1     2
2     3
ndarray    col1
0     1
1     2
2     3


In [13]:
# 2차원
col_name2 = ['col1','col2','col3']
#(2,3)
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)

#리스트로 DataFrame 생성
df_list2 = pd.DataFrame(list2, columns=col_name2)
print(df_list2)

#넘파이 ndarray로 DataFrame 생성
df_array2 = pd.DataFrame(array2, columns=col_name2)
print(df_array2)

   col1  col2  col3
0     1     2     3
1    11    12    13
   col1  col2  col3
0     1     2     3
1    11    12    13


In [14]:
# 딕셔너리로 변환

dict = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


In [15]:
#DF -> ndarray로 변환
array3 = df_dict.values
print(array3)
print(type(array3))
print(array3.shape)

# DF -> list로 변환 tolist()

list3 = df_dict.values.tolist()
print(type(list3))
print(list3)

# DF -> 딕셔너리로 변환 to_dict()
dict3 = df_dict.to_dict('list')
print(type(dict3))
print(dict3)

[[ 1  2  3]
 [11 22 33]]
<class 'numpy.ndarray'>
(2, 3)
<class 'list'>
[[1, 2, 3], [11, 22, 33]]
<class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
